version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"       # Acesso ao Jenkins
      - "50000:50000"     # Comunicação entre master e agentes (se usar agentes)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: unless-stopped

volumes:
  jenkins_home:
